// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { DocumentModel } from '../models/DocumentModel';
import IPrjData from '../interfaces/IPrjData';
import IPrjDocument from '../interfaces/IPrjDocument';
import { YamlKeyMap } from './YamlKeyMap';
import { FileType, FileSubType } from './PrjTypes';
import { toStringField } from 'src/classes/ToStringFieldDecorator';
import BaseData from './BaseData';

/**
 * Represents the data of a document.
 * @see {@link DocumentModel} for the model class.
 */
export default class DocumentData
    extends BaseData
    implements IPrjData, IPrjDocument
{
    /**
     * The type of the document.
     * @see {@link FileType}
     */
    type: FileType | null | undefined;

    /**
     * The subtype of the document.
     * @see {@link FileSubType}
     */
    subType: FileSubType | undefined;

    /**
     * The unique identifier of the document.
     * This value is generated by the system and should not be modified.
     */
    uid: string | null | undefined;

    /**
     * The title of the document.
     * @remarks This value is included in the `toString` output.
     */
    @toStringField
    title: string | null | undefined;

    /**
     * The date of the document.
     * @remarks This value is included in the `toString` output.
     * @remarks The date should be in the format `YYYY-MM-DD`.
     */
    @toStringField
    date: string | null | undefined;

    /**
     * The description of the document.
     * @remarks This value is included in the `toString` output.
     */
    @toStringField
    description: string | null | undefined;

    /**
     * The sender of the document.
     * @remarks This value is included in the `toString` output.
     */
    @toStringField
    sender: string | null | undefined;

    /**
     * The recipient of the document.
     * @remarks This value is included in the `toString` output.
     */
    @toStringField
    recipient: string | null | undefined;

    /**
     * The date of delivery of the document.
     * @remarks This value is included in the `toString` output.
     * @remarks The date should be in the format `YYYY-MM-DD`.
     */
    @toStringField
    dateOfDelivery: string | null | undefined;

    /**
     * A flag indicating if the document should be hidden in the regular view.
     */
    hide: boolean | null | undefined;

    /**
     * A flag indicating if the PDF path should not be changed automatically.
     */
    dontChangePdfPath: boolean | null | undefined;

    /**
     * The file of the document as a Obsidian Markdown link.
     * @example `[[file.ext]]`
     * @remarks This value is included in the `toString` output.
     */
    @toStringField
    file: string | null | undefined;

    /**
     * The related files of the document as a list of Obsidian Markdown links.
     * @example `[["file1.ext", "file2.ext"]]`
     * @remarks This value is included in the `toString` output.
     */
    @toStringField
    relatedFiles: string[] | null | undefined;

    /**
     * The citation title of the document for footnotes etc.
     */
    citationTitle: string | null | undefined;

    /**
     * The tags of the document.
     * @remarks This value is included in the `toString` output.
     */
    @toStringField
    tags: string | string[] | null | undefined;

    /**
     * The annotation target of the document.
     * @remarks This value is used for the `Obsidian Annotator`-Plugin.
     */
    annotationTarget: string | null | undefined;
    static yamlKeyMap: YamlKeyMap = {
        annotationTarget: 'annotation-target',
    };

    /**
     * Creates a new instance of the `DocumentData` class.
     * @param data - The data to use for the creation.
     * - If no data is provided, the default values e.g. `undefined` are used.
     * - If only partial data is provided, the missing values are set to `undefined`.
     */
    constructor(data: Partial<DocumentData>) {
        super();

        if (!data) {
            this.type = 'Metadata';

            return;
        }
        this.uid = data.uid !== undefined ? data.uid : undefined;

        this.title = data.title !== undefined ? data.title : undefined;
        this.date = data.date !== undefined ? data.date : undefined;

        this.description =
            data.description !== undefined ? data.description : undefined;
        this.sender = data.sender !== undefined ? data.sender : undefined;

        this.recipient =
            data.recipient !== undefined ? data.recipient : undefined;

        this.dateOfDelivery =
            data.dateOfDelivery !== undefined ? data.dateOfDelivery : undefined;
        this.hide = data.hide !== undefined ? data.hide : undefined;

        this.dontChangePdfPath =
            data.dontChangePdfPath !== undefined
                ? data.dontChangePdfPath
                : undefined;
        this.file = data.file !== undefined ? data.file : undefined;

        this.relatedFiles =
            data.relatedFiles !== undefined ? data.relatedFiles : undefined;

        this.citationTitle =
            data.citationTitle !== undefined ? data.citationTitle : undefined;
        this.tags = data.tags !== undefined ? data.tags : undefined;
        this.type = data.type !== undefined ? data.type : 'Metadata';
        this.subType = data.subType !== undefined ? data.subType : undefined;

        this.annotationTarget =
            data.annotationTarget !== undefined
                ? data.annotationTarget
                : undefined;
    }
}
